'use client';

import React, { useState } from 'react';
import {
  FileCode2,
  X,
  Copy,
  Check,
  Download,
  Sparkles,
  Bot,
  Terminal,
} from 'lucide-react';
import { Skill } from '@domoskills/validators';

interface AgentPromptGeneratorModalProps {
  skill: Skill | null;
  onClose: () => void;
}

type PromptTarget = 'cursorrules' | 'claudemd' | 'agentsmd' | 'chatgpt';

export function AgentPromptGeneratorModal({ skill, onClose }: AgentPromptGeneratorModalProps) {
  const [selectedTarget, setSelectedTarget] = useState<PromptTarget>('cursorrules');
  const [copied, setCopied] = useState(false);

  if (!skill) return null;

  const getGeneratedPrompt = (): string => {
    const header = `You are equipped with the specialized capability: "${skill.name}".`;
    const coreRules = `
## Role and Technical Rules
- Skill Category: ${skill.category}
- License: ${skill.license}
- Verification: ${skill.trustLevel}

### Directives & Execution Invariants:
1. Adhere strictly to the operational workflows specified for ${skill.slug}.
2. Ensure all code patterns use modern standards with explicit type safety and error handling.
3. Strictly follow safe execution boundaries: no unsanitized shell commands or hardcoded secrets.

${skill.instructions ? `### Capability Instructions:\n${skill.instructions.slice(0, 1500)}...` : ''}
`.trim();

    switch (selectedTarget) {
      case 'cursorrules':
        return `# .cursorrules for ${skill.slug}\n# Generated by DomoSkills Registry\n\n${header}\n\n${coreRules}`;
      case 'claudemd':
        return `# CLAUDE.md\n# Agent Instructions for Anthropic Claude Code\n\n${header}\n\n${coreRules}`;
      case 'agentsmd':
        return `# AGENTS.md\n# Universal Agent Directive (Antigravity & Open Agent Standards)\n\n${header}\n\n${coreRules}`;
      case 'chatgpt':
        return `[SYSTEM DIRECTIVE - ${skill.name.toUpperCase()}]\n${header}\n\n${coreRules}`;
      default:
        return coreRules;
    }
  };

  const currentContent = getGeneratedPrompt();

  const handleCopy = () => {
    navigator.clipboard.writeText(currentContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2200);
  };

  const handleDownload = () => {
    const filename =
      selectedTarget === 'cursorrules'
        ? '.cursorrules'
        : selectedTarget === 'claudemd'
        ? 'CLAUDE.md'
        : selectedTarget === 'agentsmd'
        ? 'AGENTS.md'
        : 'prompt-directive.txt';

    const blob = new Blob([currentContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const targets: { id: PromptTarget; label: string; file: string }[] = [
    { id: 'cursorrules', label: 'Cursor Rules', file: '.cursorrules' },
    { id: 'claudemd', label: 'Claude Code', file: 'CLAUDE.md' },
    { id: 'agentsmd', label: 'Antigravity / Universal', file: 'AGENTS.md' },
    { id: 'chatgpt', label: 'System Directive', file: 'Prompt Text' },
  ];

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="prompt-gen-title"
      className="fixed inset-0 z-50 overflow-y-auto bg-black/85 backdrop-blur-md p-4 sm:p-6 animate-fade-in flex items-center justify-center font-mono text-xs"
    >
      <div className="relative w-full max-w-2xl rounded-2xl border border-border bg-[#0d0d12] shadow-2xl p-6 sm:p-7 space-y-5">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-border/80 pb-4">
          <div className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-white text-black font-bold shadow-sm">
              <FileCode2 className="h-4 w-4" />
            </div>
            <div>
              <h3 id="prompt-gen-title" className="font-bold text-white text-sm">
                Zero-Install Prompt & Rules Generator
              </h3>
              <p className="text-[11px] text-text-muted">
                Direct prompt directive for <span className="text-white font-semibold">{skill.name}</span>
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="rounded-lg border border-border p-1.5 text-text-secondary hover:border-white hover:text-white transition cursor-pointer"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        {/* Target Format Tabs */}
        <div className="flex flex-wrap gap-2 pt-1">
          {targets.map((t) => {
            const isSelected = selectedTarget === t.id;
            return (
              <button
                key={t.id}
                type="button"
                onClick={() => setSelectedTarget(t.id)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg border transition cursor-pointer ${
                  isSelected
                    ? 'border-white bg-white text-black font-bold shadow-sm'
                    : 'border-border bg-surface text-text-secondary hover:text-white hover:border-border-bright'
                }`}
              >
                <span>{t.label}</span>
                <span className={`text-[10px] ${isSelected ? 'text-black/60' : 'text-text-muted'}`}>
                  ({t.file})
                </span>
              </button>
            );
          })}
        </div>

        {/* Prompt Content Preview Box */}
        <div className="relative rounded-xl border border-border bg-black p-4 text-white overflow-x-auto max-h-72">
          <pre className="whitespace-pre-wrap break-all text-[11px] leading-relaxed text-text-secondary">
            {currentContent}
          </pre>
        </div>

        {/* Action Buttons */}
        <div className="flex items-center justify-between gap-3 pt-2 border-t border-border/70">
          <button
            type="button"
            onClick={handleDownload}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl border border-border bg-surface hover:border-white text-white transition cursor-pointer"
          >
            <Download className="h-3.5 w-3.5" />
            <span>Download File</span>
          </button>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2 rounded-xl border border-border text-text-secondary hover:text-white transition cursor-pointer"
            >
              Close
            </button>

            <button
              type="button"
              onClick={handleCopy}
              className="flex items-center gap-2 px-5 py-2 rounded-xl bg-white text-black font-bold uppercase tracking-wider hover:bg-muted-white transition shadow-md cursor-pointer"
            >
              {copied ? (
                <>
                  <Check className="h-3.5 w-3.5" />
                  <span>Copied Directive!</span>
                </>
              ) : (
                <>
                  <Copy className="h-3.5 w-3.5" />
                  <span>Copy Prompt</span>
                </>
              )}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
