/**
 * expand-skills.js — rewrites skills.json with deep, accurate SKILL.md content.
 * Run: node scripts/expand-skills.js
 */

'use strict';
const fs = require('fs');
const path = require('path');

const SKILLS_PATH = path.join(__dirname, '../packages/registry/src/data/skills.json');

// Helper: join multi-line strings without template literal interpolation issues
function md(parts) {
  return parts.join('\n');
}

const SKILL_CONTENT = {};

// ─── FRONTEND ─────────────────────────────────────────────────────────────────

SKILL_CONTENT['react-performance'] = md([
'---',
'name: react-performance',
'description: Optimize React applications for rendering speed, bundle size, memoization, and component architecture.',
'license: MIT',
'version: 1.4.2',
'---',
'',
'# React Performance Optimization',
'',
'## Overview',
'React performance is about ensuring your application renders only what is necessary, when it is necessary, with minimum JavaScript sent to the browser. Poor performance manifests as jank, slow TTI, and degraded Core Web Vitals (LCP, CLS, INP).',
'',
'## 1. Profile Before Optimizing',
'- Use React DevTools Profiler (Flamegraph + Ranked view) to identify expensive components.',
'- Record a session during the exact interaction that feels slow.',
'- Look for components with high "render duration" and high "render count".',
'- Use `console.time` / `console.timeEnd` around expensive computations during development.',
'',
'## 2. Eliminate Unnecessary Re-renders',
'',
'### useMemo',
'```tsx',
'// Memoize when computation is expensive (O(n log n) or heavier)',
'const sortedItems = useMemo(() => items.slice().sort(compareFn), [items]);',
'',
'// Pointless — primitive derivation is cheaper than memo bookkeeping',
'// const count = useMemo(() => items.length, [items]);',
'```',
'',
'### useCallback',
'```tsx',
'// Stabilize callback identity passed to memoized children',
'const handleDelete = useCallback((id: string) => {',
'  dispatch({ type: "DELETE", payload: id });',
'}, [dispatch]);',
'```',
'',
'### React.memo',
'```tsx',
'// Wrap pure leaf components that receive stable props',
'export const SkillCard = React.memo(({ skill }: Props) => { ... });',
'// Do not wrap components that always re-render due to context changes',
'```',
'',
'## 3. Context Partitioning',
'Fat contexts cause every consumer to re-render on any field change.',
'',
'```tsx',
'// Bad: one giant context',
'// const AppContext = createContext({ user, theme, cart, notifications });',
'',
'// Good: split into domain-specific contexts',
'const UserContext = createContext<User | null>(null);',
'const CartContext = createContext<CartState>(defaultCart);',
'const ThemeContext = createContext<"light" | "dark">("dark");',
'```',
'',
'For high-frequency updates (mouse, scroll, animation) use Zustand, Jotai, or Valtio — React Context is not designed for >30 updates/second.',
'',
'## 4. Code Splitting & Dynamic Imports',
'```tsx',
'// Next.js',
'const HeavyChart = dynamic(() => import("./HeavyChart"), { ssr: false });',
'',
'// React Router / Vite',
'const AdminPanel = React.lazy(() => import("./AdminPanel"));',
'',
'// Rule: any component > 30KB minified should be code-split',
'```',
'',
'Target: initial JS bundle <= 100 KB gzipped; route chunks <= 50 KB gzipped.',
'',
'## 5. Virtualization for Long Lists',
'Never render more than ~200 DOM nodes in a list at once.',
'',
'```tsx',
'import { useVirtualizer } from "@tanstack/react-virtual";',
'// or',
'import { FixedSizeList } from "react-window";',
'```',
'',
'Use `react-window` for simple fixed-height rows; use `@tanstack/react-virtual` for variable-height or grid layouts.',
'',
'## 6. Image Optimization',
'- Always use `next/image` — provides lazy loading, WebP/AVIF conversion, and srcset generation.',
'- Provide explicit `width` and `height` to eliminate CLS.',
'- Use `priority` only for the largest above-the-fold image (LCP candidate).',
'',
'## 7. State Colocation',
'Keep state as close as possible to where it is consumed. Lifting state unnecessarily causes entire subtrees to re-render.',
'',
'## 8. Avoid Object/Array Literals in JSX',
'```tsx',
'// Bad: creates new reference every render, breaks memo',
'// <Component style={{ padding: 16 }} items={[a, b, c]} />',
'',
'// Good',
'const STYLE = { padding: 16 } as const;',
'<Component style={STYLE} items={ITEMS} />',
'```',
'',
'## 9. Core Web Vitals Targets',
'| Metric | Good | Needs Improvement |',
'|--------|------|-------------------|',
'| LCP | <= 2.5s | 2.5s-4.0s |',
'| INP | <= 200ms | 200ms-500ms |',
'| CLS | <= 0.1 | 0.1-0.25 |',
'',
'## 10. Anti-Patterns',
'- Using useEffect to synchronize derived state — compute it inline.',
'- Storing server data in useState — use TanStack Query or SWR.',
'- Anonymous functions in JSX passed to memoized children.',
'- Reading from Zustand inside render without selector memoization.',
'',
'## References',
'- React Compiler (React 19): https://react.dev/learn/react-compiler',
'- Million.js block-based diffing: https://million.dev',
'- Chrome DevTools Performance Panel: https://developer.chrome.com/docs/devtools/performance/',
]);

SKILL_CONTENT['nextjs-app-router'] = md([
'---',
'name: nextjs-app-router',
'description: Server Components, Server Actions, streaming SSR, caching strategies, and parallel routes in Next.js 14+.',
'license: MIT',
'version: 2.1.0',
'---',
'',
'# Next.js App Router Architecture',
'',
'## Overview',
'The App Router (stable in Next.js 14) defaults to React Server Components (RSC) which run exclusively on the server and ship zero JavaScript to the client. Understanding the server/client boundary is the single most important skill.',
'',
'## 1. Server vs. Client Component Decision Matrix',
'| Need | Use |',
'|------|-----|',
'| Data fetching from database/API | Server Component |',
'| Event handlers (onClick, onChange) | Client Component |',
'| Browser APIs (localStorage, window) | Client Component |',
'| React Hooks (useState, useEffect) | Client Component |',
'| Sensitive credentials / secrets | Server Component |',
'| Interactive UI (modals, forms) | Client Component |',
'',
'## 2. Server Component Rules',
'- Never add "use client" unless the component genuinely requires client capabilities.',
'- Push "use client" boundaries as deep as possible.',
'- Server Components can pass serializable props and JSX children to Client Components.',
'- Server Components cannot use hooks, event handlers, or browser globals.',
'',
'```tsx',
'// app/page.tsx — Server Component (no directive needed)',
'import { db } from "@/lib/db";',
'import { ProductList } from "@/components/ProductList"; // Client Component',
'',
'export default async function Page() {',
'  const products = await db.product.findMany(); // runs on server only',
'  return <ProductList products={products} />;',
'}',
'```',
'',
'## 3. Data Fetching with fetch()',
'```tsx',
'// Static: cached indefinitely',
'const data = await fetch("https://api.example.com/data", { cache: "force-cache" });',
'',
'// Dynamic: no cache, always fresh',
'const data = await fetch("https://api.example.com/data", { cache: "no-store" });',
'',
'// Revalidate every hour (ISR equivalent)',
'const data = await fetch("https://api.example.com/data", { next: { revalidate: 3600 } });',
'',
'// Tag-based revalidation',
'const data = await fetch("https://api.example.com/data", { next: { tags: ["products"] } });',
'```',
'',
'Always fetch in parallel to avoid waterfall:',
'```tsx',
'const [user, orders] = await Promise.all([fetchUser(userId), fetchOrders(userId)]);',
'```',
'',
'## 4. Server Actions',
'```tsx',
'"use server";',
'',
'import { z } from "zod";',
'import { auth } from "@/lib/auth";',
'import { revalidatePath } from "next/cache";',
'',
'const schema = z.object({ title: z.string().min(1).max(200) });',
'',
'export async function createPost(formData: FormData) {',
'  // 1. Authenticate',
'  const session = await auth();',
'  if (!session) throw new Error("Unauthorized");',
'',
'  // 2. Validate',
'  const parsed = schema.safeParse({ title: formData.get("title") });',
'  if (!parsed.success) return { error: parsed.error.flatten() };',
'',
'  // 3. Mutate',
'  await db.post.create({ data: { title: parsed.data.title, userId: session.user.id } });',
'',
'  // 4. Revalidate cache',
'  revalidatePath("/posts");',
'}',
'```',
'',
'Rules for Server Actions:',
'- Always validate with Zod before touching the database.',
'- Always authenticate the session — never trust client-passed IDs.',
'- Use revalidatePath or revalidateTag after mutations.',
'',
'## 5. Streaming with Suspense',
'```tsx',
'import { Suspense } from "react";',
'import { PostsSkeleton } from "@/components/skeletons";',
'',
'export default function Page() {',
'  return (',
'    <Suspense fallback={<PostsSkeleton />}>',
'      <SlowDataComponent />',
'    </Suspense>',
'  );',
'}',
'```',
'',
'## 6. Metadata API',
'```tsx',
'// Static',
'export const metadata: Metadata = { title: "My Page", description: "..." };',
'',
'// Dynamic',
'export async function generateMetadata({ params }: Props): Promise<Metadata> {',
'  const product = await fetchProduct(params.id);',
'  return { title: product.name, openGraph: { images: [product.image] } };',
'}',
'```',
'',
'## 7. Anti-Patterns',
'- Fetching data in Client Components on mount instead of in Server Components.',
'- Passing non-serializable props (class instances, functions) from Server to Client.',
'- Using cookies() or headers() in a layout that needs to be statically generated.',
'- Forgetting revalidatePath after Server Action mutations — stale UI.',
]);

SKILL_CONTENT['web-accessibility-a11y'] = md([
'---',
'name: web-accessibility-a11y',
'description: WCAG 2.2 AA compliance, semantic HTML, ARIA patterns, keyboard navigation, screen reader testing, and color contrast.',
'license: MIT',
'version: 1.3.0',
'---',
'',
'# Web Accessibility (a11y) — WCAG 2.2 AA',
'',
'## Overview',
'Accessibility ensures your web application is usable by people with visual, motor, auditory, and cognitive disabilities. WCAG 2.2 AA is the internationally recognized standard and a legal requirement in many jurisdictions (ADA, EU EN 301 549, UK Equality Act).',
'',
'## 1. Semantic HTML First',
'Prefer native HTML elements over ARIA-augmented divs.',
'',
'```html',
'<!-- Bad -->',
'<div class="btn" onclick="submit()">Submit</div>',
'',
'<!-- Good -->',
'<button type="submit">Submit</button>',
'```',
'',
'Landmark regions:',
'```html',
'<header role="banner">...</header>',
'<nav aria-label="Main navigation">...</nav>',
'<main id="main-content">...</main>',
'<aside aria-label="Related links">...</aside>',
'<footer role="contentinfo">...</footer>',
'```',
'',
'## 2. ARIA — Use Sparingly',
'First rule of ARIA: Do not use ARIA if an equivalent HTML element exists.',
'',
'```tsx',
'// Accessible modal',
'<div role="dialog" aria-modal="true" aria-labelledby="modal-title" aria-describedby="modal-desc">',
'  <h2 id="modal-title">Confirm Delete</h2>',
'  <p id="modal-desc">This action cannot be undone.</p>',
'</div>',
'',
'// Toggle button',
'<button aria-pressed={isActive} onClick={toggle}>',
'  {isActive ? "Active" : "Inactive"}',
'</button>',
'',
'// Combobox / autocomplete',
'<input role="combobox" aria-expanded={open} aria-autocomplete="list" aria-controls="listbox-id" />',
'<ul role="listbox" id="listbox-id">',
'  <li role="option" aria-selected={selected}>React</li>',
'</ul>',
'```',
'',
'## 3. Keyboard Navigation',
'Every interactive element must be keyboard-reachable and operable.',
'',
'| Key | Expected Behavior |',
'|-----|-------------------|',
'| Tab | Move focus forward |',
'| Shift+Tab | Move focus backward |',
'| Enter / Space | Activate button / toggle |',
'| Arrow keys | Navigate inside widget (menu, listbox, tabs) |',
'| Escape | Close modal / dismiss tooltip |',
'| Home / End | Jump to first / last item |',
'',
'Focus management in modals:',
'```tsx',
'useEffect(() => {',
'  if (isOpen) {',
'    firstFocusableRef.current?.focus();',
'  }',
'}, [isOpen]);',
'',
'// Trap focus with focus-trap-react',
'import FocusTrap from "focus-trap-react";',
'```',
'',
'## 4. Color Contrast',
'| Level | Normal Text | Large Text (18pt+) |',
'|-------|-------------|---------------------|',
'| AA | 4.5:1 | 3:1 |',
'| AAA | 7:1 | 4.5:1 |',
'',
'Never convey information by color alone — always pair with an icon, pattern, or text label.',
'',
'## 5. Images and Media',
'```html',
'<!-- Informative: describe what matters -->',
'<img src="revenue-chart.png" alt="Revenue grew 42% from Q1 to Q2 2026" />',
'',
'<!-- Decorative: empty alt suppresses screen reader announcement -->',
'<img src="background-wave.svg" alt="" role="presentation" />',
'```',
'',
'Videos must have captions. Prerecorded audio must have transcripts.',
'',
'## 6. Forms',
'```tsx',
'<label htmlFor="email">Email address</label>',
'<input',
'  id="email"',
'  type="email"',
'  required',
'  aria-required="true"',
'  aria-invalid={hasError}',
'  aria-describedby={hasError ? "email-error" : undefined}',
'/>',
'{hasError && <p id="email-error" role="alert">Please enter a valid email.</p>}',
'```',
'',
'- Use role="alert" or aria-live="polite" for dynamic error messages.',
'- Group related inputs in fieldset with legend.',
'- Never disable the submit button for invalid forms — show inline errors instead.',
'',
'## 7. Automated Testing',
'```tsx',
'import { axe, toHaveNoViolations } from "jest-axe";',
'expect.extend(toHaveNoViolations);',
'',
'it("has no accessibility violations", async () => {',
'  const { container } = render(<MyForm />);',
'  expect(await axe(container)).toHaveNoViolations();',
'});',
'```',
'',
'Manual testing checklist:',
'- Navigate entire UI with keyboard only (no mouse)',
'- Test with VoiceOver (macOS/iOS) or NVDA (Windows)',
'- Run axe DevTools or Lighthouse Accessibility audit',
'- Zoom to 200% — no horizontal scroll or content loss',
'- Disable CSS — page content is still readable/logical',
'',
'## 8. Anti-Patterns',
'- div with onClick — not keyboard accessible.',
'- aria-label text that duplicates visible label verbatim with no additional context.',
'- Removing focus outlines without providing a custom focus indicator.',
'- Auto-playing media with sound.',
'- Infinite scroll with no keyboard escape mechanism.',
]);

SKILL_CONTENT['owasp-agent-guardian'] = md([
'---',
'name: owasp-agent-guardian',
'description: OWASP Top 10 2021 secure coding rules for AI agents — injection, broken auth, SSRF, cryptographic failures, and more.',
'license: MIT',
'version: 2.0.1',
'---',
'',
'# OWASP Agent Guardian — Secure Code Generation Rules',
'',
'## Overview',
'The OWASP Top 10 (2021) defines the most critical web application security risks. This skill enforces secure patterns during code generation, preventing vulnerabilities before they enter the codebase.',
'',
'## A01 — Broken Access Control',
'Always enforce authorization checks server-side. Never trust client-provided role or permission data.',
'',
'```ts',
'// Bad: trusting client-provided userId',
'// app.get("/invoice/:id", (req, res) => { const invoice = db.getInvoice(req.query.userId, req.params.id); });',
'',
'// Good: read userId from verified session',
'app.get("/invoice/:id", requireAuth, async (req, res) => {',
'  const invoice = await db.invoice.findFirst({',
'    where: { id: req.params.id, userId: req.session.userId },',
'  });',
'  if (!invoice) return res.status(404).json({ error: "Not found" });',
'  res.json(invoice);',
'});',
'```',
'',
'## A02 — Cryptographic Failures',
'- Never store passwords in plaintext or with MD5/SHA-1.',
'- Use bcrypt (cost 12+), Argon2id, or scrypt for password hashing.',
'- Encrypt PII at rest using AES-256-GCM with a randomly generated IV per encryption.',
'- Enforce TLS 1.2+ with HSTS (Strict-Transport-Security: max-age=31536000; includeSubDomains).',
'- Never log, expose in URLs, or store secrets in environment-accessible client bundles.',
'',
'## A03 — Injection (SQL, NoSQL, OS, LDAP)',
'```ts',
'// Bad: string concatenation',
'// const user = await db.query(`SELECT * FROM users WHERE email = "${email}"`);',
'',
'// Good: parameterized query',
'const user = await db.query("SELECT * FROM users WHERE email = $1", [email]);',
'',
'// Good: ORM',
'const user = await prisma.user.findUnique({ where: { email } });',
'```',
'',
'Never pass user input to exec(), spawn() with shell:true, or eval().',
'',
'## A04 — Insecure Design',
'- Perform threat modeling (STRIDE/PASTA) before implementing sensitive features.',
'- Enforce rate limiting on authentication: max 5 attempts per 15-minute window, then exponential backoff.',
'- Design business logic to fail safely without revealing internal system state.',
'',
'## A05 — Security Misconfiguration',
'```ts',
'import helmet from "helmet";',
'app.use(helmet()); // Sets CSP, X-Frame-Options, X-Content-Type-Options, etc.',
'```',
'- Remove all default credentials, example accounts, and debug endpoints before deployment.',
'- Disable directory listing, server version headers, and stack traces in production.',
'',
'## A06 — Vulnerable and Outdated Components',
'- Run `npm audit` / `pnpm audit` in CI on every pull request.',
'- Use Dependabot or Renovate for automated dependency updates.',
'- Pin major versions and review changelogs before upgrading security-sensitive packages.',
'',
'## A07 — Identification and Authentication Failures',
'- Implement MFA for all administrative accounts.',
'- Use short-lived JWT access tokens (max 15 minutes) + long-lived refresh tokens in HttpOnly cookies.',
'- Implement account lockout after repeated failed attempts.',
'',
'## A08 — Software and Data Integrity Failures',
'- Verify checksums/signatures for downloaded artifacts in CI.',
'- Use --frozen-lockfile (pnpm) or npm ci instead of npm install in CI.',
'- Sign container images using Cosign / Notary.',
'',
'## A09 — Security Logging and Monitoring Failures',
'```ts',
'logger.warn("AUTH_FAILURE", {',
'  ip: req.ip,',
'  userAgent: req.headers["user-agent"],',
'  email: maskedEmail,',
'  timestamp: new Date().toISOString(),',
'});',
'```',
'Never log passwords, tokens, credit card numbers, or PII in plain text.',
'Set up alerts for repeated 401/403 responses, brute-force patterns, and unusual data export volumes.',
'',
'## A10 — Server-Side Request Forgery (SSRF)',
'```ts',
'// Bad: fetching user-supplied URL without validation',
'// const resp = await fetch(req.body.webhookUrl);',
'',
'// Good: allowlist specific domains only',
'const ALLOWED_DOMAINS = ["api.stripe.com", "hooks.slack.com"];',
'const url = new URL(req.body.webhookUrl);',
'if (!ALLOWED_DOMAINS.includes(url.hostname)) throw new Error("Forbidden domain");',
'const resp = await fetch(url.toString());',
'```',
'Block requests to 169.254.0.0/16 (IMDS), 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16.',
]);

SKILL_CONTENT['secret-leak-detector'] = md([
'---',
'name: secret-leak-detector',
'description: Prevent secrets, API keys, and credentials from being committed to source control or exposed in logs and responses.',
'license: MIT',
'version: 1.1.0',
'---',
'',
'# Secret Leak Detector',
'',
'## Overview',
'Accidental exposure of secrets (API keys, database URLs, private keys, OAuth tokens) is one of the most common and costly security incidents. This skill enforces patterns that make secret leakage structurally impossible.',
'',
'## 1. Environment Variables — The Only Safe Secret Store',
'```ts',
'// Good: always read from environment',
'const apiKey = process.env.STRIPE_SECRET_KEY;',
'if (!apiKey) throw new Error("STRIPE_SECRET_KEY is not configured");',
'',
'// Bad: never hardcode',
'// const apiKey = "sk_live_abc123...";',
'```',
'',
'Validate env at startup with @t3-oss/env-nextjs or zod:',
'```ts',
'import { createEnv } from "@t3-oss/env-nextjs";',
'import { z } from "zod";',
'',
'export const env = createEnv({',
'  server: {',
'    DATABASE_URL: z.string().url(),',
'    STRIPE_SECRET_KEY: z.string().startsWith("sk_"),',
'    JWT_SECRET: z.string().min(32),',
'  },',
'  runtimeEnv: process.env,',
'});',
'```',
'',
'## 2. Git Hooks — Block Commits Containing Secrets',
'Install Gitleaks or detect-secrets as a pre-commit hook:',
'```sh',
'# Gitleaks — fastest, most comprehensive',
'brew install gitleaks',
'gitleaks git --pre-commit',
'',
'# Or use Husky + detect-secrets',
'npx husky add .husky/pre-commit "detect-secrets-hook --baseline .secrets.baseline"',
'```',
'',
'## 3. .gitignore Checklist',
'Always include:',
'```',
'.env',
'.env.local',
'.env.*.local',
'.env.production',
'*.pem',
'*.key',
'*.p12',
'*.pfx',
'*.keystore',
'secrets/',
'```',
'',
'## 4. Never Log Secrets',
'```ts',
'// Bad: logs full Authorization header',
'// console.log("Request headers:", req.headers);',
'',
'// Good: redact before logging',
'const safeHeaders = { ...req.headers };',
'delete safeHeaders["authorization"];',
'delete safeHeaders["cookie"];',
'console.log("Request headers:", safeHeaders);',
'```',
'',
'## 5. Never Expose Secrets in API Responses',
'```ts',
'// Bad: returns entire user object including hashed password',
'// res.json(user);',
'',
'// Good: explicit field selection',
'const { password, stripeCustomerId, ...safeUser } = user;',
'res.json(safeUser);',
'```',
'',
'## 6. Secret Rotation Policy',
'- Rotate all secrets after any suspected exposure immediately.',
'- Prefer short-lived secrets (AWS STS temporary credentials, Vault dynamic secrets).',
'- Use secret managers: AWS Secrets Manager, HashiCorp Vault, GCP Secret Manager, Doppler.',
'',
'## 7. CI/CD — Secrets in Pipelines',
'- Use repository secrets (GitHub Actions Secrets, GitLab CI Variables) — never hardcode in YAML.',
'- Never print env vars in CI logs.',
'- If a secret appears in CI logs, rotate it immediately.',
'',
'## 8. Scanning Existing Repos',
'```sh',
'# Scan entire git history for secrets',
'gitleaks detect --source . --log-opts="--all"',
'',
'# Trufflehog — high-signal secret scanning',
'trufflehog git https://github.com/your/repo --only-verified',
'```',
'',
'If a secret is found in history: rotate immediately, then use git filter-repo or BFG Repo Cleaner to purge it.',
'',
'## 9. Anti-Patterns',
'- Committing .env files (even to private repos — repos get compromised).',
'- Using secrets as URL query parameters (?api_key=xxx appears in server logs).',
'- Logging process.env for debugging.',
'- Base64-encoding secrets and calling it "encryption".',
'- Storing secrets in localStorage or sessionStorage (XSS-accessible).',
]);

SKILL_CONTENT['fastapi-clean-architecture'] = md([
'---',
'name: fastapi-clean-architecture',
'description: FastAPI with async SQLAlchemy 2.0, Pydantic v2, dependency injection, background tasks, and clean layered architecture.',
'license: MIT',
'version: 1.5.0',
'---',
'',
'# FastAPI Clean Architecture',
'',
'## Overview',
'FastAPI is a modern Python ASGI web framework with native async/await, automatic OpenAPI documentation, and Pydantic-based validation. Clean architecture separates concerns: API routers -> Domain services -> Infrastructure repositories.',
'',
'## 1. Project Structure',
'```',
'app/',
'├── api/',
'│   ├── dependencies.py      # DI: get_db, get_current_user',
'│   └── v1/routers/          # Route handlers',
'├── core/',
'│   ├── config.py            # Settings via pydantic-settings',
'│   └── security.py          # JWT, password hashing',
'├── domain/',
'│   ├── models/              # SQLAlchemy ORM models',
'│   └── services/            # Business logic',
'├── infrastructure/',
'│   └── repositories/        # Database access layer',
'└── main.py',
'```',
'',
'## 2. Settings with Pydantic-Settings',
'```python',
'from pydantic_settings import BaseSettings, SettingsConfigDict',
'',
'class Settings(BaseSettings):',
'    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8")',
'',
'    DATABASE_URL: str',
'    SECRET_KEY: str',
'    ACCESS_TOKEN_EXPIRE_MINUTES: int = 30',
'    ENVIRONMENT: str = "development"',
'',
'settings = Settings()',
'```',
'',
'## 3. Async SQLAlchemy 2.0',
'```python',
'from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker',
'',
'engine = create_async_engine(settings.DATABASE_URL, echo=settings.ENVIRONMENT == "development")',
'AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False)',
'',
'async def get_db() -> AsyncGenerator[AsyncSession, None]:',
'    async with AsyncSessionLocal() as session:',
'        yield session',
'```',
'',
'## 4. Dependency Injection',
'```python',
'from fastapi import Depends, HTTPException, status',
'from fastapi.security import OAuth2PasswordBearer',
'',
'oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/v1/auth/token")',
'',
'async def get_current_user(',
'    token: str = Depends(oauth2_scheme),',
'    db: AsyncSession = Depends(get_db),',
') -> User:',
'    payload = decode_jwt(token)',
'    user = await user_repo.get_by_id(db, payload["sub"])',
'    if not user:',
'        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED)',
'    return user',
'```',
'',
'## 5. Pydantic v2 Schemas',
'```python',
'from pydantic import BaseModel, EmailStr, field_validator',
'from datetime import datetime',
'',
'class UserCreate(BaseModel):',
'    email: EmailStr',
'    password: str',
'    name: str',
'',
'    @field_validator("password")',
'    @classmethod',
'    def password_strength(cls, v: str) -> str:',
'        if len(v) < 8:',
'            raise ValueError("Password must be at least 8 characters")',
'        return v',
'',
'class UserResponse(BaseModel):',
'    model_config = {"from_attributes": True}  # replaces orm_mode',
'    id: int',
'    email: EmailStr',
'    name: str',
'    created_at: datetime',
'```',
'',
'## 6. Background Tasks vs Celery',
'```python',
'from fastapi import BackgroundTasks',
'',
'@router.post("/register")',
'async def register(data: UserCreate, background_tasks: BackgroundTasks, db: AsyncSession = Depends(get_db)):',
'    user = await user_service.create(db, data)',
'    background_tasks.add_task(send_welcome_email, user.email)',
'    return UserResponse.model_validate(user)',
'```',
'',
'For tasks taking >100ms, use Celery + Redis instead of BackgroundTasks.',
'',
'## 7. Global Error Handling',
'```python',
'from fastapi.exceptions import RequestValidationError',
'',
'@app.exception_handler(RequestValidationError)',
'async def validation_exception_handler(request: Request, exc: RequestValidationError):',
'    return JSONResponse(',
'        status_code=422,',
'        content={"detail": exc.errors(), "body": exc.body},',
'    )',
'```',
'',
'## 8. Health & Readiness Endpoints',
'```python',
'@app.get("/health")',
'async def health():',
'    return {"status": "ok"}',
'',
'@app.get("/readiness")',
'async def readiness(db: AsyncSession = Depends(get_db)):',
'    await db.execute(text("SELECT 1"))',
'    return {"status": "ready"}',
'```',
'',
'## 9. Anti-Patterns',
'- Synchronous database calls inside async route handlers — blocks the event loop.',
'- Business logic in route handlers — use service layer.',
'- Global mutable state — use dependency injection.',
'- Returning ORM objects directly — always transform via Pydantic schemas.',
]);

SKILL_CONTENT['rag-pipeline-architect'] = md([
'---',
'name: rag-pipeline-architect',
'description: Production-grade RAG pipeline design with chunking strategies, vector stores, hybrid search, reranking, and RAGAS evaluation.',
'license: MIT',
'version: 2.3.0',
'---',
'',
'# RAG Pipeline Architect',
'',
'## Overview',
'Retrieval-Augmented Generation (RAG) grounds LLM responses in external knowledge bases, reducing hallucinations and enabling up-to-date answers. A production RAG pipeline involves ingestion, indexing, retrieval, reranking, augmentation, and generation.',
'',
'## 1. Document Ingestion & Chunking',
'```python',
'from langchain_community.document_loaders import PDFMinerLoader',
'from langchain.text_splitter import RecursiveCharacterTextSplitter',
'',
'loader = PDFMinerLoader("technical-docs.pdf")',
'docs = loader.load()',
'',
'splitter = RecursiveCharacterTextSplitter(',
'    chunk_size=512,',
'    chunk_overlap=64,',
'    separators=["\\n\\n", "\\n", ".", " ", ""],',
')',
'chunks = splitter.split_documents(docs)',
'```',
'',
'Chunking strategy selection:',
'| Strategy | Best For |',
'|----------|----------|',
'| Fixed token size | General text, PDFs |',
'| Semantic chunking | Narrative documents, blog posts |',
'| Recursive character | Code, markdown with headers |',
'| Parent-child (hierarchical) | Multi-level documents |',
'| Sliding window | Dense technical content |',
'',
'## 2. Embedding',
'```python',
'from langchain_openai import OpenAIEmbeddings',
'',
'embeddings = OpenAIEmbeddings(model="text-embedding-3-large", dimensions=1024)',
'',
'# Open-source alternative (self-hostable)',
'from langchain_community.embeddings import HuggingFaceEmbeddings',
'embeddings = HuggingFaceEmbeddings(',
'    model_name="BAAI/bge-large-en-v1.5",',
'    encode_kwargs={"normalize_embeddings": True},',
')',
'```',
'',
'Always normalize embeddings before storing — cosine similarity of normalized vectors equals dot product (faster).',
'',
'## 3. Vector Store Indexing',
'```python',
'# pgvector (Postgres-based)',
'from langchain_postgres import PGVector',
'vectorstore = PGVector.from_documents(chunks, embeddings, connection=DATABASE_URL)',
'',
'# Qdrant (production-grade, filtering-first)',
'from langchain_qdrant import QdrantVectorStore',
'vectorstore = QdrantVectorStore.from_documents(chunks, embeddings, url=QDRANT_URL, collection_name="docs")',
'```',
'',
'## 4. Retrieval Strategies',
'',
'Dense retrieval (baseline):',
'```python',
'retriever = vectorstore.as_retriever(search_type="similarity", search_kwargs={"k": 6})',
'```',
'',
'Hybrid search (BM25 + Dense — better recall):',
'```python',
'from langchain.retrievers import EnsembleRetriever',
'from langchain_community.retrievers import BM25Retriever',
'',
'bm25_retriever = BM25Retriever.from_documents(chunks, k=4)',
'dense_retriever = vectorstore.as_retriever(search_kwargs={"k": 4})',
'',
'ensemble = EnsembleRetriever(',
'    retrievers=[bm25_retriever, dense_retriever],',
'    weights=[0.4, 0.6],',
')',
'```',
'',
'MMR for deduplication:',
'```python',
'retriever = vectorstore.as_retriever(',
'    search_type="mmr",',
'    search_kwargs={"k": 6, "fetch_k": 20, "lambda_mult": 0.7}',
')',
'```',
'',
'## 5. Reranking (Highest Leverage Optimization)',
'```python',
'from langchain.retrievers.contextual_compression import ContextualCompressionRetriever',
'from langchain_cohere import CohereRerank',
'',
'reranker = CohereRerank(model="rerank-english-v3.0", top_n=3)',
'compressed_retriever = ContextualCompressionRetriever(',
'    base_compressor=reranker,',
'    base_retriever=retriever,',
')',
'```',
'',
'## 6. Prompt with Citation',
'```python',
'SYSTEM = """Answer ONLY based on the provided context.',
'If the context does not contain the answer, say "I do not have information on that."',
'Always cite the source document name at the end of your answer.',
'',
'Context: {context}"""',
'```',
'',
'## 7. Evaluation with RAGAS',
'```python',
'from ragas import evaluate',
'from ragas.metrics import faithfulness, answer_relevancy, context_precision, context_recall',
'',
'results = evaluate(dataset=test_dataset, metrics=[faithfulness, answer_relevancy, context_precision, context_recall])',
'# Faithfulness > 0.8 is production-ready; context_precision > 0.7 is acceptable',
'```',
'',
'## 8. Advanced Techniques',
'- HyDE: Generate hypothetical answer, embed it, use to retrieve real docs.',
'- RAG-Fusion: Multiple queries per question, RRF-merge results.',
'- Self-RAG: LLM decides when to retrieve and grades its own answers.',
'- CRAG: Evaluates retrieved documents, falls back to web search if quality is low.',
'',
'## 9. Anti-Patterns',
'- Chunk size >1024 tokens — exceeds embedding model context window.',
'- No metadata filtering — every query searches entire corpus.',
'- No reranking — dense retrieval recall is high but precision is low.',
'- Not evaluating RAG systematically — gut feeling is not sufficient.',
]);

SKILL_CONTENT['postgres-query-optimizer'] = md([
'---',
'name: postgres-query-optimizer',
'description: PostgreSQL indexing strategies, EXPLAIN ANALYZE interpretation, query planning, vacuum tuning, and connection pooling.',
'license: MIT',
'version: 1.7.0',
'---',
'',
'# PostgreSQL Query Optimizer',
'',
'## Overview',
'PostgreSQL is the most advanced open-source relational database. Its query planner relies on accurate statistics and proper indexing. Understanding EXPLAIN ANALYZE, index types, vacuuming, and connection pooling is essential for production performance.',
'',
'## 1. EXPLAIN ANALYZE — Reading Query Plans',
'```sql',
'EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON)',
'SELECT u.id, u.name, COUNT(o.id) AS order_count',
'FROM users u',
'LEFT JOIN orders o ON o.user_id = u.id',
'WHERE u.created_at > NOW() - INTERVAL "30 days"',
'GROUP BY u.id, u.name',
'ORDER BY order_count DESC',
'LIMIT 20;',
'```',
'',
'Key nodes:',
'| Node | Meaning |',
'|------|---------|',
'| Seq Scan | Full table scan — often bad on large tables |',
'| Index Scan | Uses B-tree index — good |',
'| Index Only Scan | No heap fetch — excellent |',
'| Bitmap Heap Scan | Combines multiple indexes — good for OR |',
'| Hash Join | Good for large sets, no sort requirement |',
'| Nested Loop | Good when inner set is small |',
'',
'Warning signs: rows=10000 actual=1 (bad statistics — run ANALYZE); Seq Scan on table >10K rows with selective WHERE (missing index).',
'',
'## 2. Index Types',
'',
'B-tree (default — 90% of use cases):',
'```sql',
'CREATE INDEX CONCURRENTLY idx_orders_user_id ON orders (user_id);',
'CREATE INDEX CONCURRENTLY idx_users_email ON users (email) WHERE deleted_at IS NULL; -- partial',
'CREATE INDEX CONCURRENTLY idx_orders_composite ON orders (user_id, created_at DESC); -- composite',
'```',
'',
'Always use CONCURRENTLY in production to avoid locking the table.',
'',
'GIN (Full-text search and JSONB):',
'```sql',
'-- Full-text search',
'ALTER TABLE articles ADD COLUMN tsv tsvector GENERATED ALWAYS AS (',
'  to_tsvector("english", coalesce(title,"") || " " || coalesce(body,""))',
') STORED;',
'CREATE INDEX CONCURRENTLY idx_articles_tsv ON articles USING GIN (tsv);',
'',
'-- JSONB containment',
'CREATE INDEX CONCURRENTLY idx_events_metadata ON events USING GIN (metadata jsonb_path_ops);',
'SELECT * FROM events WHERE metadata @> \'{"type": "purchase"}\';',
'```',
'',
'BRIN (time-series / sequential data):',
'```sql',
'CREATE INDEX CONCURRENTLY idx_logs_created_at ON logs USING BRIN (created_at);',
'```',
'',
'## 3. Common Query Optimizations',
'',
'Keyset pagination (instead of OFFSET):',
'```sql',
'-- Bad: OFFSET is O(n) — slow at high offsets',
'-- SELECT * FROM posts ORDER BY id DESC OFFSET 10000 LIMIT 20;',
'',
'-- Good: keyset pagination — O(log n) with index',
'SELECT * FROM posts WHERE id < $last_id ORDER BY id DESC LIMIT 20;',
'```',
'',
'Window functions for running totals:',
'```sql',
'SELECT',
'  date_trunc("day", created_at) AS day,',
'  SUM(amount) AS daily_revenue,',
'  SUM(SUM(amount)) OVER (ORDER BY date_trunc("day", created_at)) AS cumulative_revenue',
'FROM orders',
'GROUP BY day',
'ORDER BY day;',
'```',
'',
'## 4. Autovacuum Tuning',
'```sql',
'-- Check table bloat',
'SELECT relname, n_dead_tup, n_live_tup,',
'  round(n_dead_tup::numeric / NULLIF(n_live_tup + n_dead_tup, 0) * 100, 2) AS dead_pct',
'FROM pg_stat_user_tables',
'ORDER BY n_dead_tup DESC;',
'',
'-- Aggressive autovacuum for high-update tables',
'ALTER TABLE orders SET (',
'  autovacuum_vacuum_scale_factor = 0.01,',
'  autovacuum_analyze_scale_factor = 0.005',
');',
'```',
'',
'## 5. Connection Pooling with PgBouncer',
'```ini',
'[pgbouncer]',
'pool_mode = transaction      ; most efficient',
'max_client_conn = 1000',
'default_pool_size = 25       ; = max_connections / num_app_instances',
'```',
'',
'Rule: max_connections in postgresql.conf should never exceed CPU cores * 4.',
'',
'## 6. Anti-Patterns',
'- SELECT * in production — fetches unnecessary columns, prevents index-only scans.',
'- Indexes on low-cardinality columns (boolean, 3-value status).',
'- Functions in WHERE on indexed columns: WHERE LOWER(email) = $1 bypasses index.',
'  Fix: CREATE INDEX ON users (LOWER(email)) instead.',
'- Not running VACUUM ANALYZE after large bulk imports.',
'- Using NOT IN with subqueries — use NOT EXISTS or LEFT JOIN / IS NULL instead.',
]);

SKILL_CONTENT['docker-container-hardening'] = md([
'---',
'name: docker-container-hardening',
'description: Docker image security, multi-stage builds, non-root users, read-only filesystems, resource limits, and supply chain verification.',
'license: MIT',
'version: 1.8.0',
'---',
'',
'# Docker Container Hardening',
'',
'## Overview',
'A default Docker container runs as root, uses a mutable filesystem, and has no resource bounds. Container hardening removes these attack surfaces and limits blast radius if a container is compromised.',
'',
'## 1. Multi-Stage Builds — Minimal Final Image',
'```dockerfile',
'# Stage 1: Build',
'FROM node:20-alpine AS builder',
'WORKDIR /app',
'COPY package*.json ./',
'RUN npm ci --frozen-lockfile',
'COPY . .',
'RUN npm run build',
'',
'# Stage 2: Runtime — only what is needed',
'FROM node:20-alpine AS runner',
'WORKDIR /app',
'',
'RUN addgroup --system --gid 1001 nodejs && \\',
'    adduser --system --uid 1001 nextjs',
'',
'COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./',
'COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static',
'COPY --from=builder --chown=nextjs:nodejs /app/public ./public',
'',
'USER nextjs',
'EXPOSE 3000',
'ENV NODE_ENV=production PORT=3000 HOSTNAME="0.0.0.0"',
'CMD ["node", "server.js"]',
'```',
'',
'## 2. Non-Root User (Required)',
'```dockerfile',
'RUN groupadd -r appgroup && useradd -r -g appgroup -u 1001 appuser',
'USER appuser',
'```',
'Verify: docker run --rm your-image id — must NOT print uid=0(root).',
'',
'## 3. Read-Only Root Filesystem',
'```yaml',
'services:',
'  app:',
'    image: myapp:latest',
'    read_only: true',
'    tmpfs:',
'      - /tmp:uid=1001,gid=1001,size=100m',
'      - /run:uid=1001,gid=1001',
'```',
'',
'## 4. Drop Linux Capabilities',
'```yaml',
'services:',
'  app:',
'    cap_drop:',
'      - ALL',
'    cap_add:',
'      - NET_BIND_SERVICE  # Only if binding to ports < 1024',
'```',
'',
'## 5. Resource Limits (Required)',
'```yaml',
'services:',
'  app:',
'    deploy:',
'      resources:',
'        limits:',
'          cpus: "1.5"',
'          memory: 512M',
'        reservations:',
'          cpus: "0.25"',
'          memory: 128M',
'```',
'Without limits, a single runaway container can starve the host.',
'',
'## 6. Image Scanning in CI',
'```yaml',
'- name: Scan image',
'  uses: aquasecurity/trivy-action@master',
'  with:',
'    image-ref: myapp:latest',
'    format: table',
'    exit-code: 1',
'    severity: HIGH,CRITICAL',
'    ignore-unfixed: true',
'```',
'',
'## 7. Image Signing (Supply Chain)',
'```sh',
'# Cosign keyless signing with GitHub OIDC',
'cosign sign --yes ghcr.io/myorg/myapp:latest',
'',
'# Verify',
'cosign verify ghcr.io/myorg/myapp:latest \\',
'  --certificate-identity=https://github.com/myorg/myapp/.github/workflows/build.yml@refs/heads/main \\',
'  --certificate-oidc-issuer=https://token.actions.githubusercontent.com',
'```',
'',
'## 8. .dockerignore',
'```',
'.git',
'.env',
'.env.local',
'node_modules',
'dist',
'*.log',
'tests/',
'.github/',
'```',
'',
'## 9. Anti-Patterns',
'- FROM ubuntu:latest — pinless tags break reproducibility; use ubuntu:22.04@sha256:...',
'- RUN apt-get install without --no-install-recommends — bloats image.',
'- Storing secrets in Dockerfile ENV or ARG — visible in image history via docker history.',
'- --privileged containers — grants ALL Linux capabilities, equivalent to root on the host.',
'- Mounting /var/run/docker.sock — allows container escape.',
]);

SKILL_CONTENT['playwright-e2e-suite'] = md([
'---',
'name: playwright-e2e-suite',
'description: Playwright E2E testing — Page Object Model, network interception, visual regression, CI parallelization, and auth state management.',
'license: MIT',
'version: 1.6.0',
'---',
'',
'# Playwright E2E Testing Suite',
'',
'## Overview',
'Playwright is Microsoft\'s cross-browser E2E testing framework. It drives real browsers (Chromium, Firefox, WebKit) with a single API, with first-class support for auto-waiting, network interception, visual regression, and accessibility testing.',
'',
'## 1. Project Configuration',
'```ts',
'// playwright.config.ts',
'import { defineConfig, devices } from "@playwright/test";',
'',
'export default defineConfig({',
'  testDir: "./e2e",',
'  fullyParallel: true,',
'  forbidOnly: !!process.env.CI,',
'  retries: process.env.CI ? 2 : 0,',
'  workers: process.env.CI ? 4 : undefined,',
'  reporter: [["html"], ["junit", { outputFile: "results.xml" }]],',
'  use: {',
'    baseURL: process.env.BASE_URL ?? "http://localhost:3000",',
'    trace: "on-first-retry",',
'    screenshot: "only-on-failure",',
'    video: "retain-on-failure",',
'  },',
'  projects: [',
'    { name: "chromium", use: { ...devices["Desktop Chrome"] } },',
'    { name: "firefox", use: { ...devices["Desktop Firefox"] } },',
'    { name: "webkit", use: { ...devices["Desktop Safari"] } },',
'    { name: "Mobile Chrome", use: { ...devices["Pixel 7"] } },',
'  ],',
'  webServer: {',
'    command: "npm run dev",',
'    url: "http://localhost:3000",',
'    reuseExistingServer: !process.env.CI,',
'  },',
'});',
'```',
'',
'## 2. Page Object Model (POM)',
'```ts',
'// e2e/pages/LoginPage.ts',
'import { type Page, type Locator, expect } from "@playwright/test";',
'',
'export class LoginPage {',
'  readonly emailInput: Locator;',
'  readonly passwordInput: Locator;',
'  readonly submitButton: Locator;',
'  readonly errorMessage: Locator;',
'',
'  constructor(private page: Page) {',
'    this.emailInput = page.getByLabel("Email address");',
'    this.passwordInput = page.getByLabel("Password");',
'    this.submitButton = page.getByRole("button", { name: "Sign in" });',
'    this.errorMessage = page.getByRole("alert");',
'  }',
'',
'  async goto() { await this.page.goto("/login"); }',
'',
'  async login(email: string, password: string) {',
'    await this.emailInput.fill(email);',
'    await this.passwordInput.fill(password);',
'    await this.submitButton.click();',
'  }',
'',
'  async expectError(message: string) {',
'    await expect(this.errorMessage).toContainText(message);',
'  }',
'}',
'```',
'',
'## 3. Auth State Management (Reuse Sessions)',
'```ts',
'// Save auth state once, reuse across all tests',
'// playwright.config.ts',
'// use: { storageState: "e2e/.auth/user.json" }',
'',
'// e2e/setup/auth.setup.ts',
'import { test as setup } from "@playwright/test";',
'',
'setup("authenticate", async ({ page }) => {',
'  await page.goto("/login");',
'  await page.getByLabel("Email").fill(process.env.TEST_EMAIL!);',
'  await page.getByLabel("Password").fill(process.env.TEST_PASSWORD!);',
'  await page.getByRole("button", { name: "Sign in" }).click();',
'  await page.waitForURL("/dashboard");',
'  await page.context().storageState({ path: "e2e/.auth/user.json" });',
'});',
'```',
'',
'## 4. Network Interception & Mocking',
'```ts',
'// Mock an API response',
'await page.route("**/api/products", route =>',
'  route.fulfill({',
'    status: 200,',
'    contentType: "application/json",',
'    body: JSON.stringify([{ id: 1, name: "Test Product" }]),',
'  })',
');',
'',
'// Abort analytics requests',
'await page.route("**/*analytics*", route => route.abort());',
'```',
'',
'## 5. Visual Regression Testing',
'```ts',
'await expect(page).toHaveScreenshot("home-page.png", {',
'  maxDiffPixels: 100,',
'  threshold: 0.2,',
'  mask: [page.locator(".dynamic-timestamp")], // mask volatile content',
'});',
'```',
'Update snapshots: npx playwright test --update-snapshots',
'',
'## 6. Accessibility Testing',
'```ts',
'import { checkA11y, injectAxe } from "axe-playwright";',
'',
'test("no a11y violations on home page", async ({ page }) => {',
'  await page.goto("/");',
'  await injectAxe(page);',
'  await checkA11y(page);',
'});',
'```',
'',
'## 7. Anti-Patterns',
'- page.waitForTimeout(3000) — brittle; use waitForSelector, waitForURL, or auto-waiting.',
'- CSS selectors like .btn-primary-12xf3 — use getByRole, getByLabel, getByTestId.',
'- Tests sharing mutable state — always reset DB state between test runs.',
'- Single worker sequential runs — wastes 5-10x time; always parallelize.',
]);

SKILL_CONTENT['turborepo-pipeline-caching-mastery'] = md([
'---',
'name: turborepo-pipeline-caching-mastery',
'description: Turborepo task pipelines, remote caching, package graph analysis, generator scaffolding, and monorepo developer experience.',
'license: MIT',
'version: 1.4.0',
'---',
'',
'# Turborepo Pipeline & Caching Mastery',
'',
'## Overview',
'Turborepo is a high-performance build system for JavaScript/TypeScript monorepos. Its core value propositions are: (1) intelligent task graph scheduling that runs tasks in parallel where safe, (2) content-addressed local and remote caching, and (3) dependency-aware incremental builds.',
'',
'## 1. turbo.json Pipeline Configuration',
'```json',
'{',
'  "$schema": "https://turbo.build/schema.json",',
'  "globalDependencies": [".env", "tsconfig.base.json"],',
'  "pipeline": {',
'    "build": {',
'      "dependsOn": ["^build"],',
'      "outputs": [".next/**", "dist/**", "!.next/cache/**"],',
'      "env": ["NODE_ENV", "NEXT_PUBLIC_*"]',
'    },',
'    "test": {',
'      "dependsOn": ["build"],',
'      "outputs": ["coverage/**"],',
'      "cache": true',
'    },',
'    "lint": { "outputs": [] },',
'    "type-check": { "dependsOn": ["^build"], "outputs": [] },',
'    "dev": { "cache": false, "persistent": true }',
'  }',
'}',
'```',
'',
'dependsOn patterns:',
'| Pattern | Meaning |',
'|---------|---------|',
'| "^build" | Must build all workspace deps first |',
'| "build" | Must run its own build task first |',
'| [] | No dependencies — runs immediately |',
'| "$MY_VAR" | Depends on env variable value |',
'',
'## 2. Remote Caching with Vercel',
'```sh',
'npx turbo login',
'npx turbo link',
'```',
'',
'In CI, pass TURBO_TOKEN and TURBO_TEAM env variables to enable remote cache hits across all runners.',
'Self-hosted alternative: turborepo-remote-cache (open-source) for air-gapped environments.',
'',
'## 3. Package Graph Analysis',
'```sh',
'# Visualize task execution graph',
'npx turbo build --graph',
'',
'# Run only affected packages since main branch',
'npx turbo build --filter="...[origin/main]"',
'',
'# Run for a specific package and its dependents',
'npx turbo test --filter=@myapp/ui...',
'',
'# Run only for packages that changed since last commit',
'npx turbo build --filter="[HEAD^1]"',
'```',
'',
'## 4. Workspace Package Structure',
'```',
'my-monorepo/',
'├── apps/',
'│   ├── web/            # Next.js app',
'│   └── docs/',
'├── packages/',
'│   ├── ui/             # Shared React components',
'│   ├── config/         # Shared ESLint, TS, Tailwind configs',
'│   └── utils/',
'├── turbo.json',
'└── package.json',
'```',
'',
'Internal package exports (for TypeScript + pnpm workspaces):',
'```json',
'{',
'  "name": "@myapp/ui",',
'  "exports": {',
'    ".": {',
'      "import": "./dist/index.mjs",',
'      "require": "./dist/index.js"',
'    }',
'  },',
'  "scripts": {',
'    "build": "tsup src/index.ts --format esm,cjs --dts",',
'    "dev": "tsup src/index.ts --format esm,cjs --dts --watch"',
'  }',
'}',
'```',
'',
'## 5. Generator Scaffolding',
'```sh',
'npx turbo gen workspace --name @myapp/new-package --type package',
'```',
'',
'## 6. CI Integration (GitHub Actions)',
'```yaml',
'jobs:',
'  build:',
'    runs-on: ubuntu-latest',
'    env:',
'      TURBO_TOKEN: TURBO_TOKEN_SECRET',
'      TURBO_TEAM: my-team',
'    steps:',
'      - uses: actions/checkout@v4',
'        with: { fetch-depth: 2 }',
'      - uses: pnpm/action-setup@v3',
'      - run: pnpm install --frozen-lockfile',
'      - run: pnpm turbo build test lint type-check',
'```',
'',
'## 7. Anti-Patterns',
'- Non-deterministic output in outputs (timestamps in filenames) — pollutes cache.',
'- Missing "^build" in dependsOn — causes race conditions.',
'- Setting cache: false on tasks that should be cached.',
'- Not specifying env in pipeline tasks that use environment variables — cache misses will not occur when env changes.',
]);

// ─── Load, apply, save ──────────────────────────────────────────────────────
const skills = JSON.parse(fs.readFileSync(SKILLS_PATH, 'utf-8'));

let updatedCount = 0;
let skippedCount = 0;
const remainingSlugs = [];

for (const skill of skills) {
  const content = SKILL_CONTENT[skill.slug];
  if (content) {
    skill.instructions = content;
    updatedCount++;
  } else {
    skippedCount++;
    remainingSlugs.push(skill.slug + ' (' + (skill.instructions || '').length + ' chars)');
  }
}

fs.writeFileSync(SKILLS_PATH, JSON.stringify(skills, null, 2), 'utf-8');
console.log('\n=== Skills Expansion Report ===');
console.log('Updated with deep content: ' + updatedCount);
console.log('Left unchanged: ' + skippedCount);
console.log('\nSlug | Original chars | New chars:');
skills.filter(s => SKILL_CONTENT[s.slug]).forEach(s => {
  console.log(' + ' + s.slug + ': ' + (SKILL_CONTENT[s.slug] || '').length + ' chars');
});
